site_name: lcobucci/jwt
theme: readthedocs

nav:
  - 'index.md'
  - 'installation.md'
  - 'configuration.md'
  - 'issuing-tokens.md'
  - 'parsing-tokens.md'
  - 'validating-tokens.md'
  - 'extending-the-library.md'

markdown_extensions:
  - admonition
